import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
//import App from './App';
//import Secondscreen from './Secondscreen';
import Fourthscreen from './Fourthscreen';
import Thirdscreen from './Thirdscreen';
import registerServiceWorker from './registerServiceWorker';
ReactDOM.render(<Fourthscreen />, document.getElementById('root'));
registerServiceWorker();
